---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    
---

```{r setup, include = FALSE, message = FALSE}
library(flexdashboard)
library(plotly)
library(p8105.datasets)
library(tidyverse)
data("ny_noaa")


#Theme
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

## dataset prep
ny_noaa =
  ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month", "day_of_month")) %>% 
  mutate(
        tmax = as.numeric(tmax),
        tmin = as.numeric(tmin),
        year = as.numeric(year),
        month = as.numeric(month),
        day_of_month = as.numeric(day_of_month)
        ) %>% 
  mutate(
        prcp = (prcp / 10),
        tmax = (tmax / 10),
        tmin = (tmin / 10),
        ) %>% 
  filter(year %in% c(2010))

#for testing:
# rmarkdown::render("dashboard_template.Rmd", output_format = "flexdashboard::flex_dashboard")

```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r boxplot, message = F, warning = False}
ny_noaa %>% 
  mutate(
    text_label = str_c("Date:", month, "/", day_of_month, "/", year, "\nMax Temperature:", tmax),
     month = as.factor(month),
      month = recode(month, `1` = "Jan", `2` = "Feb", `3` = "Mar", 
                        `4` = "April", `5` = "May", `6` = "Jun", 
                        `7` = "Jul", `8` = "August", `9` = "Sep",
                        `10` = "Oct", `11` = "Nov", `12` = "Dec")) %>%
  group_by(id, year, month, day_of_month) %>%
  plot_ly(
    x = ~month, y = ~tmax, color = ~month, text = ~text_label, alpha = 0.5,
    type = "box") %>% 
    layout(title = 'Monthly Max Temperatures in NY State per Month, 2010',
           yaxis = list(title = 'Max Temperature'),
           xaxis = list(title = 'Month'))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r scatter plot}
ny_noaa %>% 
  mutate(
    text_label = str_c("Date:", month, "/", day_of_month, "/", year, "\nMax Temperature:", tmax)
    ) %>% 
  filter(month %in% c(1, 8)) %>% 
  mutate(month = as.factor(month),
         month = recode(month, `1` = "January", `8` = "August")) %>% 
  group_by(id, year, month, day_of_month) %>%
  plot_ly(
    x = ~day_of_month, y = ~tmax, color = ~month, text = ~text_label, alpha = 0.5,
    type = "scatter", mode = "markers") %>% 
    layout(title = 'Daily Max Temperatures per Selected Months, NY State, 2010',
           yaxis = list(title = 'Max Temperature'))
```

### Chart C

```{r lines plot}
ny_noaa_sampled = 
  ny_noaa %>% 
  sample_n(1000)

ny_noaa_sampled %>% 
  mutate(
     month = as.factor(month),
      month = recode(month, `1` = "Jan", `2` = "Feb", `3` = "Mar", 
                        `4` = "April", `5` = "May", `6` = "Jun", 
                        `7` = "Jul", `8` = "August", `9` = "Sep",
                        `10` = "Oct", `11` = "Nov", `12` = "Dec"),
     text_label = str_c("Day of the Month:", day_of_month, "\n MM Preciptation:", prcp)) %>%
  group_by(id, year, month, day_of_month) %>%
  plot_ly(
    x = ~month, y = ~prcp, 
    alpha = 1, 
    text = ~text_label,
    type = 'bar') %>% 
    layout(title = 'Millimeters of Precipitation in NY State, 2010',
           showlegend = FALSE,
           xaxis = list(title = 'Month',
           yaxis = list(title = 'MM Precipitation')))
```



